network:
    logging:
        enabled: false
        level: BODY # HttpLoggingInterceptor.Level{NONE, BASIC, HEADERS, BODY}
logging:
    enabled: false
    show_hashs: false
performance:
    show_memory_leaks: false
    dev_metrics: false
    stetho: false
errors:
    rethrow: false
crashes:
    enabled: true
    additional_data: true
    max_network: 100
    max_trace: 100
    max_component: 100
    # Change app_id in stubs.yml, preprod.yml, prod.yml and release.yml
